title: "Uğurcan Yıldız Academic CV"
email: "ugurcanyildiz34@gmail.com"
description: "Personal academic CV of Uğurcan Yıldız"
baseurl: ""
url: "https://ugurcanyildiz.github.io"
theme: jekyll-theme-cayman
